name: Deploy to GitHub Pages Repo

on:
  workflow_run:
    workflows: ["Release Addon ZIP"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Get tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Download artifact from release
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }}
          tag: ${{ github.event.workflow_run.head_branch }}
          fileName: "*.zip"
          out-file-path: "./dist"

      - name: Clone GitHub Pages repo
        uses: actions/checkout@v3
        with:
          repository: shelomito12/shelomito12.github.io
          token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          path: site

      - name: Copy zip file
        run: |
          ZIP_NAME=$(ls dist/*.zip | xargs -n 1 basename)
          VERSION="${ZIP_NAME##*-}"           # 1.0.0.zip
          VERSION="${VERSION%.zip}"           # remove .zip
          mkdir -p site/zips/plugin.video.guemara/$VERSION
          cp dist/*.zip site/zips/plugin.video.guemara/$VERSION/plugin.video.guemara.zip

      - name: Push to GitHub Pages
        run: |
          cd site
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add release $VERSION"
          git push
