name: Deploy latest ZIP to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon repo
        uses: actions/checkout@v3

      - name: Set addon ID and version
        shell: bash
        run: |
          ADDON_ID=$(grep -Po 'id="\K[^"]+' addon.xml)
          VERSION=$(basename "${GITHUB_REF}")
          echo "ADDON_ID=$ADDON_ID" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create ZIP
        run: |
          ZIP_NAME="${ADDON_ID}-${VERSION}.zip"
          zip -r "$ZIP_NAME" * .[^.]* -x '*.git*' '*.github*'
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone GitHub Pages repo
        uses: actions/checkout@v3
        with:
          repository: shelomito12/shelomito12.github.io
          token: ${{ secrets.GH_RELEASE_PAT }}
          path: site

      - name: Copy new ZIP
        run: |
          cp "${ZIP_NAME}" site/

      - name: Keep only latest 5 ZIPs
        run: |
          cd site
          ls -tp *.zip | grep -v '/$' | tail -n +6 | xargs -r rm --

      - name: Generate index.html with only latest ZIP
        run: |
          cd site
          LATEST_ZIP=$(ls -1 *.zip | sort -Vr | head -n 1)
          echo '<!DOCTYPE html>' > index.html
          echo "<a href=\"$LATEST_ZIP\">$LATEST_ZIP</a>" >> index.html

      - name: Commit and push changes
        run: |
          cd site
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy $ZIP_NAME"
          git push
