name: Deploy latest ZIP to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon repo
        uses: actions/checkout@v3

      - name: Set addon ID and version
        run: |
          ADDON_ID=$(grep -Po 'id="\K[^"]+' addon.xml)
          echo "ADDON_ID=$ADDON_ID" >> $GITHUB_ENV
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create ZIP
        run: |
          ZIP_NAME="${ADDON_ID}-${VERSION}.zip"
          zip -r "$ZIP_NAME" * .[^.]* -x '*.git*' '*.github*'

      - name: Clone GitHub Pages repo
        uses: actions/checkout@v3
        with:
          repository: shelomito12/shelomito12.github.io
          token: ${{ secrets.GH_RELEASE_PAT }}
          path: site

      - name: Purge old ZIPs (keep 5 newest)
        run: |
          mkdir -p site
          cd site
          rm -f *.zip
          cd ..

      - name: Copy new ZIP and generate index.html
        run: |
          cp "${ADDON_ID}-${VERSION}.zip" site/
          cd site
          echo '<!DOCTYPE html>' > index.html
          echo "<a href=\"${ADDON_ID}-${VERSION}.zip\">${ADDON_ID}-${VERSION}.zip</a>" >> index.html

      - name: Commit and push changes
        run: |
          cd site
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy ${ADDON_ID}-${VERSION}.zip"
          git push
