name: Deploy latest ZIP to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon repo
        uses: actions/checkout@v3

      - name: Set addon ID and version
        run: |
          ADDON_ID=$(grep -Po 'id="\K[^"]+' addon.xml)
          echo "ADDON_ID=$ADDON_ID" >> $GITHUB_ENV
          VERSION=$(echo "${GITHUB_REF}" | sed -E 's|refs/tags/v?||')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create ZIP
        run: |
          ZIP_NAME="${ADDON_ID}-${VERSION}.zip"
          zip -r "../$ZIP_NAME" * .[^.]* -x '*.git*' '*.github*'

      - name: Clone GitHub Pages repo
        uses: actions/checkout@v3
        with:
          repository: shelomito12/shelomito12.github.io
          token: ${{ secrets.GH_RELEASE_PAT }}
          path: site

      - name: Copy new ZIP
        run: |
          cp "../${ADDON_ID}-${VERSION}.zip" site/

      - name: Keep only latest 5 ZIPs
        run: |
          cd site
          ls -tp *.zip | grep -v '/$' | tail -n +6 | xargs -r rm --

      - name: Generate index.html with only latest ZIP
        run: |
          cd site
          LATEST_ZIP=$(ls -1 *.zip | sort -Vr | head -n 1)
          echo '<!DOCTYPE html>' > index.html
          echo "<a href=\"$LATEST_ZIP\">$LATEST_ZIP</a>" >> index.html

      - name: Commit and push changes
        run: |
          cd site
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy ${{ env.ADDON_ID }}-${{ env.VERSION }}.zip"
          git push
