name: Deploy to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon repo
        uses: actions/checkout@v3

      - name: Set addon ID and version
        run: |
          ADDON_ID=$(grep -Po 'id="\K[^"]+' addon.xml)
          echo "ADDON_ID=$ADDON_ID" >> $GITHUB_ENV
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create ZIP file
        run: |
          ZIP_NAME="${ADDON_ID}-${VERSION}.zip"
          zip -r "$ZIP_NAME" * .[^.]* -x '*.git*' '*.github*'

      - name: Clone GitHub Pages repo
        uses: actions/checkout@v3
        with:
          repository: shelomito12/shelomito12.github.io
          token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          path: site

      - name: Copy ZIP to pages repo
        run: |
          mkdir -p site/zips/${{ env.ADDON_ID }}
          cp "${{ env.ADDON_ID }}-${{ env.VERSION }}.zip" "site/zips/${{ env.ADDON_ID }}/"

      - name: Generate latest index.html
        run: |
          cd site/zips/${{ env.ADDON_ID }}
          LATEST_ZIP=$(ls -1 plugin.video.guemara-*.zip | sort -Vr | head -n 1)
          echo "<ul>" > index.html
          echo "  <li><a href=\"$LATEST_ZIP\">$LATEST_ZIP</a></li>" >> index.html
          echo "</ul>" >> index.html

      - name: Commit and push
        run: |
          cd site
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add release ${{ env.VERSION }}"
          git push
