name: Release and Deploy Addon ZIP

on:
  push:
    tags:
      - 'v*'
  release:
    types:
      - published

env:
  VERSION: ${{ github.ref_name }}

jobs:
  release_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon source
        uses: actions/checkout@v4

      - name: Extract addon ID and ZIP name
        run: |
          ADDON_ID=$(grep -Po 'id="\K[^"]+' addon.xml)
          ZIP_NAME="${ADDON_ID}-${VERSION}.zip"
          echo "ADDON_ID=$ADDON_ID" >> $GITHUB_ENV
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Create ZIP file
        run: |
          zip -r "${ZIP_NAME}" * .[^.]* -x '*.git*' '*.github*' 'zips/*' '*.zip'

      - name: Clone GitHub Pages repo
        uses: actions/checkout@v4
        with:
          repository: shelomito12/shelomito12.github.io
          token: ${{ secrets.GH_RELEASE_PAT }}
          path: site

      - name: Move existing ZIPs to archive and copy new ZIP
        run: |
          mkdir -p site/archives
          mv site/*.zip site/archives/ 2>/dev/null || true
          cp "$ZIP_NAME" site/
      
      - name: Cleanup archives, keeping only latest 3 ZIPs
        run: |
          cd site/archives
          ls -tp *.zip 2>/dev/null | grep -v '/$' | tail -n +4 | xargs -r rm --
      
      - name: Generate index.html in root of Pages repo
        run: |
          cd site
          echo -e '<!DOCTYPE html>\n<a href="'${ZIP_NAME}'">'${ZIP_NAME}'</a>' > index.html

      - name: Commit and push changes to GitHub Pages
        run: |
          cd site
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy $ZIP_NAME"
          git push