name: Release Addon ZIP

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract tag name (version)
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Extract addon ID from addon.xml
        run: |
          ADDON_ID=$(grep -Po 'id="\K[^"]+' addon.xml)
          echo "ADDON_ID=$ADDON_ID" >> $GITHUB_ENV

      - name: Create ZIP file
        run: |
          ZIP_NAME="${ADDON_ID}-${TAG_NAME}.zip"
          zip -r "$ZIP_NAME" * .[^.]* -x '*.git*' '*.github*'

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.ADDON_ID }}-${{ env.TAG_NAME }}.zip
          tag_name: ${{ env.TAG_NAME }}
          files: ./${{ env.ADDON_ID }}-${{ env.TAG_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
