name: Release and Deploy Addon ZIP

on:
  push:
    tags:
      - 'v*'

env:
  VERSION: ${{ github.ref_name }}

jobs:
  release_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract addon ID and ZIP name
        run: |
          ADDON_ID=$(grep -Po 'id="\K[^"]+' addon.xml)
          ZIP_NAME="${ADDON_ID}-${VERSION}.zip"
          echo "ADDON_ID=$ADDON_ID" >> $GITHUB_ENV
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Create ZIP file
        run: |
          zip -r "${ZIP_NAME}" * .[^.]* -x '*.git*' '*.github*'
          
      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          files: ./${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_PAT }}

      - name: Clone GitHub Pages repo
        uses: actions/checkout@v4
        with:
          repository: shelomito12/shelomito12.github.io
          token: ${{ secrets.GH_RELEASE_PAT }}

      - name: Copy ZIP and generate index.html in root of Pages repo
        run: |
          cp "../${ZIP_NAME}" .
          echo -e '<!DOCTYPE html>\n<a href="'${ZIP_NAME}'">'${ZIP_NAME}'</a>' > index.html

      - name: Keep only latest 5 ZIPs in root
        run: |
          ls -tp *.zip | grep -v '/$' | tail -n +6 | xargs -r rm --

      - name: Commit and push changes to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy $ZIP_NAME"
          git push
