name: Release Addon ZIP

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set addon ID
        id: addon
        run: |
          ADDON_ID=$(grep -Po 'id="\K[^"]+' addon.xml)
          echo "ADDON_ID=${ADDON_ID}" >> $GITHUB_ENV

      - name: Create zip file
        run: |
          zip -r "${{ env.ADDON_ID }}-${{ env.TAG_NAME }}.zip" * .[^.]* -x "*.git*" "*.github*"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.ADDON_ID }}-${{ env.TAG_NAME }}.zip
          tag_name: ${{ env.TAG_NAME }}
          files: ./${{ env.ADDON_ID }}-${{ env.TAG_NAME }}.zip
        env:
          token: ${{ secrets.GH_RELEASE_PAT }}
